apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-gpu-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cdi-gpu-depl
  template:
    metadata:
      labels:
        app: cdi-gpu-depl
    spec:
      nodeSelector:
        storage: "cdi"
      containers:
        - name: test-cdi-fpga
          image: busybox
          volumeMounts:
          - mountPath: "/cdi"
            name: cdi-volume
          command: [ "sleep", "1000000" ]
      volumes:
        - name: cdi-volume
          ephemeral:
            volumeClaimTemplate:
              metadata:
                annotations:
                  memory: "2000000000"
                  millicores: "300"
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: gpusc
                resources:
                  requests:
                    storage: 1