apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-gpu-depl2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdi-gpu-depl2
  template:
    metadata:
      labels:
        app: cdi-gpu-depl2
    spec:
      nodeSelector:
        storage: "cdi"
      containers:
        - name: test-cdi-fpga
          image: busybox
          volumeMounts:
          - mountPath: "/cdi"
            name: cdi-volume
          command: [ "sleep", "1000000" ]
      volumes:
        - name: cdi-volume
          persistentVolumeClaim:
            claimName: gpuclaim2
