apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpuclaim2
  annotations:
    memory: "2000000000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1 # storage request is mandatory for pvc
  storageClassName: gpusc2
